/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Tiko (https://sketchfab.com/tikoavp)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cheese-moon-7cbba11da66245329aaff0cba3896b2b
Title: Cheese Moon
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber' 

const CheeseMoon=(props)=> {
  const { nodes, materials } = useGLTF('/Portfolio/models/cheese_moon.glb')
  const moonRef = useRef()
  
  useFrame((state, delta) => {
    moonRef.current.rotation.y += delta * 0.5 
    moonRef.current.position.y = Math.sin(state.clock.getElapsedTime()) * 0.2 // 上下浮动
  })


  return (
    <group  ref={moonRef} {...props} dispose={null}>
      <group scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Moon001_Cheese_0.geometry}
          material={materials.Cheese}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/Portfolio/models/cheese_moon.glb')
export default CheeseMoon;