/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: zixisun02 (https://sketchfab.com/zixisun51)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/shiba-faef9fe5ace445e7b2989d1c1ece361c
Title: Shiba
*/

import React from 'react'
import { Float, useGLTF } from '@react-three/drei'

const   Dog=(props)=> {
  const { nodes, materials } = useGLTF('/models/shiba.glb')
  return (
    <Float
    speed={4}         
    rotationIntensity={1} 
    floatIntensity={2}   
    floatingRange={[0, 0.3]} 
  >
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Group18985_default_0.geometry}
        material={materials['default']}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box002_default_0.geometry}
        material={materials['default']}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object001_default_0.geometry}
        material={materials['default']}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
    </Float>
  )
}

useGLTF.preload('/models/shiba.glb')
export default Dog;